plugins {
    id "com.android.library"
    id "kotlin-android"
}

android {
    namespace "com.android.sdk.net.rxjava2"

    compileSdk rootProject.properties["app.compileSdk"] as int

    defaultConfig {
        minSdk rootProject.properties["app.minSdk"] as int
        targetSdk rootProject.properties["app.targetSdk"] as int
    }

    lintOptions {
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
        freeCompilerArgs += ["-Xcontext-receivers"]
    }
}

tasks.register('javadoc', Javadoc) {
    options.encoding = "utf-8"
}

dependencies {
    api project(":lib_network")
    api "io.reactivex.rxjava2:rxjava:2.2.21"
    api "com.squareup.retrofit2:adapter-rxjava2:2.9.0"
    implementation "androidx.annotation:annotation:1.8.2"
    implementation "com.jakewharton.timber:timber:4.7.1"
}